default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: chat_system_development

test:
  <<: *default
  database: chat_system_test

production:
  <<: *default
  database: chat_system_production
  username: chat_system
  password: <%= ENV['CHAT_SYSTEM_DATABASE_PASSWORD'] %>
