:concurrency: 10
:queues:
  - default

:scheduler:
  :schedule:
    update_counts_job:
      cron: "*/30 * * * *" # Every 30 minutes
      class: "UpdateCountsJob"

    process_messages_job:
      cron: "*/1 * * * *" # Every 1 minute
      class: "ProcessMessagesJob"

    process_chats_job:
      cron: "*/1 * * * *" # Every 1 minute
      class: "ProcessChatsJob"
